# Generated by Django 3.2.6 on 2022-03-22 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='product.category'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='pr_img',
            field=models.ImageField(upload_to='product/'),
        ),
    ]
