# Generated by Django 3.2.6 on 2022-03-22 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220322_0858'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_ordered',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='items',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='refrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refrence', to='cart.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ManyToManyField(related_name='items', to='product.Product'),
        ),
    ]
