# Generated by Django 3.2.6 on 2022-03-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220322_0858'),
        ('cart', '0003_auto_20220322_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ManyToManyField(related_name='items', to='product.Product'),
        ),
    ]
